export enum NotificationType {
  SUBSCRIPTION_INVITE = 'SUBSCRIPTION_INVITE',
  PAYMENT_DUE = 'PAYMENT_DUE',
  PAYMENT_RECEIVED = 'PAYMENT_RECEIVED',
  PAYMENT_FAILED = 'PAYMENT_FAILED',
  NEW_MESSAGE = 'NEW_MESSAGE',
  SUBSCRIPTION_EXPIRING = 'SUBSCRIPTION_EXPIRING',
  MEMBER_JOINED = 'MEMBER_JOINED',
  MEMBER_LEFT = 'MEMBER_LEFT',
  SYSTEM = 'SYSTEM',
  REVIEW_RECEIVED = 'REVIEW_RECEIVED'
} 